base_path: /extension/_locales
commit_message: "Fix:  New translations for (%language%) from Crowdin.  [ci skip]"
append_commit_message: "false"
files:
  - source: /en/*.json
    translation: /%locale%/%original_file_name%
