name: CI PR Build Download Comment

on:
  workflow_run:
    workflows: [CI]
    types:
      - completed
    branches-ignore:
      - '_archived__**'
    paths-ignore:
      - '**/README.md'

permissions:
  actions: read
  pull-requests: write

jobs:
  precheck:
    name: Check if workflow needs to execute
    runs-on: ubuntu-latest
    outputs:
      runWorkflow: ${{ steps.checkci.outputs.result }}
    if: github.event.workflow_run.conclusion == 'success' || github.event.workflow_run.event == 'pull_request' || github.event.workflow_run.event == 'pull_request_target'
    steps:
      - name: Check Result
        id: checkci
        env:
          COMMIT_API: ${{ github.event.repository.commits_url }}
          GH_GH: ${{ toJson(github) }}
          FROM_CI_EVENT: ${{ github.event.workflow_run.event }}
          PR_HEADBRANCH: ${{ github.event.workflow_run.head_branch }}
          PR_HEADSHA: ${{ github.event.workflow_run.head_sha }}
          PR_HEADMSG: ${{ github.event.workflow_run.head_commit.message }}
          PR_NUM: ${{ github.event.workflow_run.pull_requests[0].number }}
          PR_RUNID: ${{ github.event.workflow_run.id }}
          PR_CHECKID: ${{ github.event.workflow_run.check_suite_id }}
        run: |
          echo "PR Run ID                        : $PR_RUNID"
          echo "From CI Event                    : $FROM_CI_EVENT"
          echo "PR Number                        : $PR_NUM"
          echo "Head Branch Ref                  : $PR_HEADBRANCH"
          echo "PR Head Commit SHA               : $PR_HEADSHA"
          SKIP_A=$([[ "$PR_HEADBRANCH" == l10n_* ]] && echo true || echo false)
          echo "Skip if branch starts with l10n_ : $SKIP_A"
          echo "Commit Message:\n$PR_HEADMSG"
          EXP_SKIP="\[ci skip]"
          SKIP_B=$([[ "$PR_HEADMSG" =~ $EXP_SKIP ]] && echo true || echo false)
          echo "Skip via Commit Msg              : $SKIP_B"
          RES=$([[ $SKIP_A == true || $SKIP_B == true ]] && echo true || echo false)
          echo "Skip CI                          : $RES"
          echo "::set-output name=result::$RES"
  upload_coverage:
    name: Coverage Uploads
    runs-on: ubuntu-latest
    needs: precheck
    if: needs.precheck.outputs.runWorkflow
    steps:
      - name: Download coverage artifact
        uses: actions/download-artifact@v3
        with:
          name: coverage
      - name: List files
        run: |
          ls -anl
  download_comment:
    name: Generate PR Build Download Comment
    runs-on: ubuntu-latest
    needs: precheck
    if: needs.precheck.outputs.runWorkflow
    steps:
      - name: 'Echo available stuff'
        env:
          GH_GH: ${{ toJson(github) }}
        run: |
          echo "Check env log above for details"
      - name: 'Generate PR Run Info from previous workflow'
        id: workflowArtifacts
        uses: actions/github-script@v6
        with:
          script: |
            let allArtifacts = await github.rest.actions.listWorkflowRunArtifacts({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context.payload.workflow_run.id,
            });
            if (allArtifacts.data.total_count < 2) {
              console.log(`Artifact count is ${allArtifacts.data.total_count}. Not generating comment.`);
              return;
            }
            let buildArtifacts = allArtifacts.data.artifacts.filter((a) => {
              return a.name.indexOf('Cookie-AutoDelete') !== -1 && !a.expired
            }).map((a) => {
              return {
                id: a.id,
                name: a.name,
                created_at: a.created_at,
                expires_at: a.expires_at,
                artifact_url: `${context.payload.workflow_run.head_repository.html_url}/suites/${context.payload.workflow_run.check_suite_id}/artifacts/${a.id}`,
              }
            });
            console.log(buildArtifacts);
            return buildArtifacts;
        
