name: CI PR Build Download Comment

on:
  workflow_run:
    workflows: [CI]
    types:
      - completed
    branches-ignore:
      - '_archived__**'
    paths-ignore:
      - '**/README.md'

permissions:
  actions: read
  pull-requests: write

jobs:
  download_comment:
    name: Generate PR Build Download Comment
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: 'Echo available stuff'
        env:
          GH_GH: ${{ toJson(github) }}
        run: |
          echo "Check env log above for details"
      - name: 'Generate PR Run Info from previous workflow'
        uses: actions/github-script@v6
        with:
          script: |
            let allArtifacts = await github.rest.actions.listWorkflowRunArtifacts({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context.payload.workflow_run.id,
            });
            if (allArtifacts.data.total_count < 2) {
              console.log(`Artifact count is ${allArtifacts.data.total_count}. Not generating comment.`);
              return;
            }
            let buildArtifacts = allArtifacts.data.artifacts.filter((a) => {
              return a.name.indexOf('Cookie-AutoDelete') !== -1 && !a.expired
            }).map((a) => {
              return {
                id: a.id,
                name: a.name,
                created_at: a.created_at,
                expires_at: a.expires_at,
                artifact_url: `${context.payload.workflow_run.head_repository.html_url}/suites/${context.payload.workflow_run.check_suite_id}/artifacts/${a.id}`,
              }
            });
            console.log(buildArtifacts);
